baseurl: /blog
destination: dist
email: your-email@example.com
github_username: aaronjameslang
linkedin_username: aaronjameslang
markdown: kramdown
source: src
theme: minima
title: aaronjamesla.ng
url: https://ajla.ng
