baseurl: /blog
email: your-email@example.com
github_username: aaronjameslang
linkedin_username: aaronjameslang
markdown: kramdown
theme: minima
title: aaronjamesla.ng
url: https://ajla.ng
exclude:
- Gemfile
- Gemfile.lock
- vendor
- venv
