baseurl: /blog
destination: docs
email: your-email@example.com
github_username: aaronjameslang
linkedin_username: aaronjameslang
markdown: kramdown
source: src
theme: minima
title: blog.ajla.ng
url: https://blog.ajla.ng
